apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: study
data:
  elasticsearch.yml: |
    cluster.name: "${NAMESPACE}"
    node.name: "${POD_NAME}"
    cluster.initial_master_nodes: elasticsearch-0,elasticsearch-1,elasticsearch-2
    discovery.seed_hosts: elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch
    # bootstrap.memory_lock: true
    network.host: "${POD_NAME}"
    http.bind_host: "${POD_NAME}"
    transport.port: 9300
    http.port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: study
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: tcp
    port: 9300
    protocol: TCP
  - name: http
    port: 9200
    protocol: TCP
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-node
  namespace: study
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: tcp
    port: 9300
    protocol: TCP
    nodePort: 30930
  - name: http
    port: 9200
    protocol: TCP
    nodePort: 30920
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: study
  labels:
    app: elasticsearch
spec:
  replicas: 3
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.12.0
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          limits:
            cpu: '500m'
            memory: 1Gi
          requests:
            cpu: '500m'
            memory: 1Gi
        volumeMounts:
          - name: elasticsearch-config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch
