apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: frontend
  name: frontend-demo
  namespace: study
spec:
  containers:
  - image: nginx:1.16
    imagePullPolicy: IfNotPresent
    name: php-redis