apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-cluster-admin
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: default
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion:  rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-admin
rules:
  - apiGroups: [""]
    resources: ["deployments", "pods", "services", "statefullsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
