apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-app-task-run
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-app
  # trigger:
  #   type: manual
  inputs:
    resources:
      - name: tekton-demo
        resourceRef:
          name: git-pipeline-resource
    params:
      - name: pathToDockerFile
        value: Dockerfile
      - name: pathToContext
        value: /workspace/tekton-demo
      - name: pathToYaml
        value: /workspace/tekton-demo/deployment.yaml
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: registry-pipeline-resource