apiVersion: v1
kind: Service
metadata:
  name: remotedev
spec:
  selector:
    app: remotedev
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    name: ssh
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http1
  - port: 8081
    targetPort: 8080
    nodePort: 30081
    name: http2
  type: NodePort
