kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: study
  name: pdb-demo
spec:
  replicas: 15
  selector:
    matchLabels:
      app: pdb-demo
  template:
    metadata:
      labels:
        app: pdb-demo
    spec:
      containers:
        - name: pause
          image: registry.cn-shenzhen.aliyuncs.com/bingk8s/pause:3.2
      affinity:                                                             #限制pod只分布在node节点
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - "node"
