apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-pub
  namespace: study
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
    nodePort: 30092
  selector:
    app: kafka
  type: NodePort