apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: base-service
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    version: "5.7"
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-pub
  namespace: base-service
spec:
  selector:
    app: mysql
    version: "5.7"
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32306
  type: NodePort

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: base-service
stringData:
  root-pass: "Hello2021"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: base-service
  labels:
    version: "5.7"
data:
  master.cnf: |
    [mysqld]
    collation_server = utf8mb4_general_ci
    character_set_server = utf8mb4
    skip-host-cache
    skip-name-resolve
    datadir         = /var/lib/mysql
    default_storage_engine = InnoDB
    default-time-zone = '+8:00'
    tmp_table_size = 32M
    max_heap_table_size = 32M
    query_cache_type = 0
    query_cache_size = 0
    max_connections = 102400
    thread_cache_size = 256
    table_open_cache = 10240
    open_files_limit = 655350
    innodb_buffer_pool_size = 2G
    innodb_log_file_size = 128M
    innodb_file_per_table = 1
    innodb_flush_method = O_DIRECT
    wait_timeout=2880000
    interactive_timeout=2880000
    max_allowed_packet=256M
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    log_error = /var/log/mysql/error.log
    slow_query_log_file = /var/log/mysql/slow.log
    slow_query_log = 1
    [client]
    default_character_set=utf8

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: base-service
spec:
  selector:
    matchLabels:
      app: mysql
      version: "5.7"
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        version: "5.7"
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root-pass
              name: mysql-pass
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: log
          mountPath: /var/log/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d/master.cnf
          subPath: master.cnf
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 3Gi
        livenessProbe:
          exec:
            command: ["env", "&&", "mysqladmin", "-uroot", "-pHello2021", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["env", "&&", "mysql",  "-uroot", "-pHello2021", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: conf
        configMap:
          name: mysql
      - name: data
        hostPath:
          path: /www/data/mysql
      nodeSelector:
        ssd: "true"
  volumeClaimTemplates:
  - metadata:
      name: log
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: alinas