kind: Pod
apiVersion: v1
metadata:
  name: pod3
  labels:
    foo: bar
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        foo: bar
  containers:
  - name: pause
    image: registry.cn-shenzhen.aliyuncs.com/bingk8s/pause:3.2